### PR TITLE
Add bioinformatics pipelines

### PR DESCRIPTION
**Pull request by pwwang**

### CODE REVIEW

**Comment by erictleung** [comment]
@pwwang thanks for the addition. Have you used all or some of these pipelines at some level? Also, some of these pipelines (like the first six) appear to be general pipeline development, not genomics focused. So my opinion is that these more general ones will add noise to the other pipelines listed.

@danielecook what do you think of adding the general purpose pipeline sites?

**Comment by danielecook** [comment]
It's a long list and there is a lot of variation. I would filter based on the following criteria:

- open source
- command-line/scripting based (avoid GUI)
- must work w/in cluster environments. 

Most of them are probably fine, but I would start by removing KNIME, Gene Pattern, Chipster, and ugene. I can look through them more thoroughly early next week.

**Comment by danielecook** [comment]
It's a long list and there is a lot of variation. I would filter based on the following criteria:

- open source
- command-line/scripting based (avoid GUI)
- must work w/in cluster environments. 

Most of them are probably fine, but I would start by removing KNIME, Gene Pattern, Chipster, and ugene. I can look through them more thoroughly early next week.

**Comment by pwwang** [comment]
I will create a new pull request and try to filter out some based on @danielecook 's criteria, and my own experience.

**Pull request closed without merging**
