### PR TITLE
Add command line utility shournal

### PR DESCRIPTION
**Pull request by tycho-kirchner**
shournal tracks commands and used files on the shell and its invoked programs, facilitating a safer, more reproducible usage of the command-line. *How did I create that file last week* can then be answered within seconds.

### CODE REVIEW

**Comment by danielecook** [comment]
This is not a bioinformatics tool.

**Comment by tycho-kirchner** [comment]
> This is not a bioinformatics tool.

And neither is GNU Parallel, [CSVKit](https://github.com/wireservice/csvkit) or [datamash](https://git.savannah.gnu.org/gitweb/?p=datamash.git). That's why I placed in under category *Data Processing/Command Line Utilities*. shournal is a tool to actually make it feasible to redo a command you executed last week. Being a bioinformatician myself and having worked in a computational biology research group for years I'm confident that this is not a niche problem in the scientific community. And I suppose the editors of our meanwhile [published paper](https://doi.org/10.1038/s41598-024-53811-9) would agree. GNU Parallel is for sure the more important tool, so a more appropriate rejection comment from your side would be "not important enough to include here" -- an opinion which I of course disagree, which is however more objectively justified.

Thanks, Tycho

**Comment by danielecook** [comment]
> "not important enough to include here"

This is not my position.

Look, it's a great tool and paper and I'm sure it's helpful to researchers, but your tool fits a broader use case than bioinformatics. I would prefer to feature tools that are (a) designed to work on biological data or (b) solve a frequent problem encountered when working with biological data.

To make myself clear: I do think it's an important tool. I just don't think it's relevant here.

**Comment by tycho-kirchner** [comment]
Thank you for the clarification.

**Pull request closed without merging**
